name: cloutbook
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl:
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  flutter_slidable: ^0.6.0
  mobx: 2.0.1
  flutter_mobx: 2.0.0
  equatable: ^2.0.0
  dio: ^4.0.0
  pretty_dio_logger: ^1.1.1
  injectable: 1.2.2
  get_it: 6.1.1
  auto_route: ^1.0.2
  jiffy: ^4.1.0
  flutter_hooks: 0.16.0
  photo_view: ^0.11.1
  flutter_parsed_text: ^2.1.0
  flutter_inappwebview: ^5.3.2
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  url_launcher: ^6.0.3
  font_awesome_flutter: 9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  injectable_generator: 1.2.2
  hive_generator: ^1.0.1
  auto_route_generator: ^1.0.2
  mobx_codegen: 2.0.1+3
  flutter_launcher_icons: "0.9.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app-icon.png"

flutter:
  uses-material-design: true

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Light.ttf
        - asset: assets/fonts/SFProDisplay-Regular.ttf
        - asset: assets/fonts/SFProDisplay-Medium.ttf
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
        - asset: assets/fonts/SFProDisplay-Heavy.ttf
        - asset: assets/fonts/SFProDisplay-Black.ttf

  assets:
    - assets/images/